replicaCount: 1

image:
  repository: ghcr.io/mschulte/nixhorn-webhook
  pullPolicy: IfNotPresent
  tag: "0.1.0"

webhook:
  port: 8443

  # PATH that's patched into each longhorn container's PATH.
  # see: https://github.com/NixOS/nixpkgs/blob/c7e10647eadb53b7cf3552a53e8bb33c8248c8c3/pkgs/applications/networking/cluster/k3s/docs/examples/STORAGE.md
  pathPatch: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/run/wrappers/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"

  longhornNamespace: "longhorn-system"

  # @schema
  # required: false
  # enum: [Ignore,Fail]
  failurePolicy: Ignore

  timeoutSeconds: 10

  # @schema
  # oneOf:
  #   - required: [cert, key]
  #     properties:
  #       type:
  #         const: literal
  #       cert:
  #         type: string
  #       key:
  #         type: string
  #   - required: [name]
  #     properties:
  #       type:
  #         const: secret
  #       name:
  #         type: string
  # @schema
  tls:
    type: insecure

# Admission controller security context.
securityContext: {}

service:
  type: ClusterIP
  port: 443

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
