apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patch-longhorn-manager-adm-ctl.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patch-longhorn-manager-adm-ctl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "patch-longhorn-manager-adm-ctl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/tls: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "patch-longhorn-manager-adm-ctl.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "patch-longhorn-manager-adm-ctl.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: webhook
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --port={{ .Values.webhook.port }}
        - --tls-cert-file=/etc/tls/tls.crt
        - --tls-key-file=/etc/tls/tls.key
        - --longhorn-namespace={{ .Values.webhook.longhornNamespace }}
        - --path-patch={{ .Values.webhook.pathPatch }}
        ports:
        - name: https
          containerPort: {{ .Values.webhook.port }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: {{ include "patch-longhorn-manager-adm-ctl.tlsSecretName" . }}
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
