apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "nixhorn-webhook.fullname" . }}
  labels:
    {{- include "nixhorn-webhook.labels" . | nindent 4 }}
webhooks:
- name: {{ include "nixhorn-webhook.fullname" . }}.{{ .Values.webhook.longhornNamespace }}.svc.cluster.local
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "nixhorn-webhook.fullname" . }}
      path: /mutate
    {{- if eq .Values.webhook.tls.type "insecure" }}
    {{- $certData := include "nixhorn-webhook.genCerts" . | fromYaml }}
    caBundle: {{ $certData.caBundle }}
    {{- else if and (eq .Values.webhook.tls.type "literal") .Values.webhook.tls.cert }}
    caBundle: {{ .Values.webhook.tls.cert | b64enc }}
    {{- else }}
    caBundle: ""
    {{- end }}
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ .Values.webhook.longhornNamespace }}
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  failurePolicy: {{ .Values.webhook.failurePolicy }}
