apiVersion: v1
kind: Service
metadata:
  name: {{ include "patch-longhorn-manager-adm-ctl.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patch-longhorn-manager-adm-ctl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: https
  selector:
    {{- include "patch-longhorn-manager-adm-ctl.selectorLabels" . | nindent 4 }}
