apiVersion: v1
kind: Service
metadata:
  name: {{ include "nixhorn-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nixhorn-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.webhook.port }}
    protocol: TCP
    name: https
  selector:
    {{- include "nixhorn-webhook.selectorLabels" . | nindent 4 }}
