replicaCount: 1

image:
  repository: ghcr.io/mschulte/nixhorn-webhook
  pullPolicy: IfNotPresent
  # @schema
  # required: false
  # type: string
  # description: Container image tag. Defaults to .Chart.AppVersion if not specified
  # @schema
  tag: ""

webhook:
  port: 8443

  # PATH that's patched into each longhorn container's PATH.
  # see: https://github.com/NixOS/nixpkgs/blob/c7e10647eadb53b7cf3552a53e8bb33c8248c8c3/pkgs/applications/networking/cluster/k3s/docs/examples/STORAGE.md
  pathPatch: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/run/wrappers/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"

  longhornNamespace: "longhorn-system"

  # @schema
  # required: false
  # enum: [Ignore,Fail]
  # @schema
  failurePolicy: Ignore

  timeoutSeconds: 10

  # @schema
  # required: false
  # oneOf:
  #   - type: object
  #     properties:
  #       type:
  #         const: insecure
  #         description: Uses pre-generated certificates from chart files (default)
  #     required: [type]
  #   - type: object
  #     properties:
  #       type:
  #         const: secret
  #       name:
  #         type: string
  #         description: References an existing Kubernetes secret by name
  #     required: [type, name]
  # @schema
  tls:
    type: insecure

# Admission controller security context.
securityContext: {}

service:
  type: ClusterIP
  port: 443

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
